"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestOOnozTestsModelStatistics,
	#superclass : #PackageManifest,
	#category : 'OOnoz-Tests-Model-Statistics'
}

{ #category : #'code-critics' }
ManifestOOnozTestsModelStatistics class >> ruleGRAnsiConvertorRuleV1FalsePositive [
	^ #(#(#(#RGClassDefinition #(#OOMCQResultTest)) #'2016-11-05T00:06:57.76034+01:00') )
]
