Extension { #name : #OOAdminRole }

{ #category : #'*OOnoz-WebApplication-Core' }
OOAdminRole class >> displayName [
	^ 'Administrateur'
]

{ #category : #'*OOnoz-WebApplication-Core' }
OOAdminRole class >> logToAdminApplication [
	^ true
]

{ #category : #'*OOnoz-WebApplication-Core' }
OOAdminRole class >> setRole [
	^ true
]

{ #category : #'*OOnoz-WebApplication-Core' }
OOAdminRole class >> validateMCQs [
	^ true
]
