Extension { #name : #OOStrictScheme }

{ #category : #'*OOnoz-WebApplication-Core' }
OOStrictScheme class >> description [
	^ 'L''utilisateur marque des points sur les questions uniquement si toutes les réponses sont juste. Si une réponse fausse a été cochée ou qu''une réponse juste n''a pas été cochée, l''utilisateur ne marquera pas de point.'
]

{ #category : #'*OOnoz-WebApplication-Core' }
OOStrictScheme class >> label [
	^ 'Conformité stricte'
]
