language: smalltalk
sudo: false

os:
  - linux
  - osx

install:
  - pip install --user benchupload

smalltalk:
  - Pharo-6.0
  - Pharo-5.0

matrix:
  allow_failures:
    - smalltalk: Pharo-6.0

notifications:
  email:
    recipients:
      - c.ferlicot-delbecque@etudiant.univ-lille1.fr
      - maxime.piquet@etudiant.univ-lille1.fr
    on_success: never
    on_failure: always

# bob-bench xUnit file analysis
after_success:
  - benchupload --dir=$SMALLTALK_CI_BUILD
after_failure:
  - benchupload --dir=$SMALLTALK_CI_BUILD