language: smalltalk
sudo: false

os:
- linux
- osx

smalltalk:
  - Pharo-6.0
  - Pharo-5.0

matrix:
  allow_failures:
    - smalltalk: Pharo-6.0

notifications:
  email:
    recipients:
      - c.ferlicot-delbecque@etudiant.univ-lille1.fr
      - maxime.piquet@etudiant.univ-lille1.fr
    on_success: never
    on_failure: always