language: smalltalk
sudo: false

os:
  - linux
  - osx

install:
  - pip install --user benchupload

smalltalk:
  - Pharo64-7.0
  - Pharo64-6.1

matrix:
  fast_finish: true
  allow_failures:
    - smalltalk: Pharo64-7.0

notifications:
  email:
    recipients:
      - cyril.ferlicot@gmail.com
    on_success: never
    on_failure: always

# bob-bench xUnit file analysis
after_success:
  - benchupload --dir=$SMALLTALK_CI_BUILD
after_failure:
  - benchupload --dir=$SMALLTALK_CI_BUILD