javascript
oonozCss
	^ '.oonoz-badges{
  display: flex;	
}

.panel-default>.panel-heading .badge.badge-success{
background-color:rgba(139,195,74 ,1);
}

.panel-default>.panel-heading .badge.badge-danger{
background-color:rgba(244,67,54,1);
}

.alert 
{ 
  border: 2px solid transparent !important; 
background-color: transparent !important;
} 
 
.alert-danger 
{ 
  border-color:rgba(244,67,54,1) !important; 
  color:rgba(244,67,54,1) !important; 
} 
 
.alert-success 
{ 
  border-color: rgba(139,195,74 ,1) !important; 
  color: rgba(139,195,74 ,1) !important; 
} 
 
.alert-primary 
{ 
  border-color:rgba(33,150,243 ,1) !important; 
  color:rgba(33,150,243 ,1) !important; 
}'