"
An OOStrictSchemeTest is a test class for testing the behavior of OOStrictScheme
"
Class {
	#name : #OOStrictSchemeTest,
	#superclass : #OOAbstractMarkingSchemeStrategyTest,
	#category : 'OOnoz-Tests-Model-MarkingScheme'
}

{ #category : #accessing }
OOStrictSchemeTest >> actualClass [
	^ OOStrictScheme
]

{ #category : #helpers }
OOStrictSchemeTest >> allCheckedResult [
	^ 0
]

{ #category : #helpers }
OOStrictSchemeTest >> nothingCheckedResult [
	^ 0
]
