"
An OOStrictWithPenalitySchemeTest is a test class for testing the behavior of OOStrictWithPenalityScheme
"
Class {
	#name : #OOStrictWithPenalitySchemeTest,
	#superclass : #OOAbstractMarkingSchemeStrategyTest,
	#category : 'OOnoz-Tests-Model-MarkingScheme'
}

{ #category : #accessing }
OOStrictWithPenalitySchemeTest >> actualClass [
	^ OOStrictWithPenalityScheme
]

{ #category : #helpers }
OOStrictWithPenalitySchemeTest >> allCheckedResult [
	^ -1
]

{ #category : #helpers }
OOStrictWithPenalitySchemeTest >> allWrongResult [
	^ -1
]

{ #category : #helpers }
OOStrictWithPenalitySchemeTest >> nothingCheckedResult [
	^ -1
]
